### ISSUE TITLE
RuntimeError: User specified an unsupported autocast device_type 'cuda:0'

### ISSUE THREAD

**Issue by 0smboy** [karpathy/build-nanogpt#44]

**Comment by 0smboy** [comment]
torchrun --standalone --nproc_per_node=8 train_mystar.py 
W0630 13:10:51.400042 140616219449152 torch/distributed/run.py:757] 
W0630 13:10:51.400042 140616219449152 torch/distributed/run.py:757] *****************************************
W0630 13:10:51.400042 140616219449152 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0630 13:10:51.400042 140616219449152 torch/distributed/run.py:757] *****************************************
[W socket.cpp:697] [c10d] The client socket has failed to connect to [gpu]:60437 (errno: 22 - Invalid argument).
[W socket.cpp:697] [c10d] The client socket has failed to connect to [gpu]:60437 (errno: 22 - Invalid argument).
[W socket.cpp:697] [c10d] The client socket has failed to connect to [gpu]:60437 (errno: 22 - Invalid argument).
[W socket.cpp:697] [c10d] The client socket has failed to connect to [gpu]:60437 (errno: 22 - Invalid argument).
total desired batch size is: 524288
=>calculated gradient accumulation steps is: 4
loaded 338025 tokens
[rank1]: Traceback (most recent call last):
[rank1]:   File "train_mystar.py", line 342, in <module>
[rank1]:     with torch.autocast(device_type=device, dtype=torch.bfloat16):
[rank1]:   File "/home/foreknow/myenv/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 241, in __init__
[rank1]:     raise RuntimeError(
[rank1]: RuntimeError: User specified an unsupported autocast device_type 'cuda:1'
[rank6]: Traceback (most recent call last):
[rank6]:   File "train_mystar.py", line 342, in <module>
[rank6]:     with torch.autocast(device_type=device, dtype=torch.bfloat16):
[rank6]:   File "/home/foreknow/myenv/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 241, in __init__
[rank6]:     raise RuntimeError(
[rank6]: RuntimeError: User specified an unsupported autocast device_type 'cuda:6'
num decayed parameter tensors: 50, with 124,354,560 parameters
num non-decayed parameter tensors: 98, with 121,344 parameters
using fused AdamW: True
